# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bb9f3ee50c5337e6dc17767d4ea79b62bcaf112a136fab3b5127caa89634819bec7ed201b037f11ef403cda0ff537a21d11741bd1aa99ab42ed86e75dcae68b

test:
  secret_key_base: d56b55b33fbdd4d51bddfdd699c6e7a29a73c4b8dc03de34dc8185cc50dd8324d9cdabb738d98880019072fe29ddaebffc6f48a73d63630f960aa7fd4334dc6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
